name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature*
  pull_request:
    branches:
      - main
      - feature*

jobs:
  build_and_deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deployed to Dev
        run: echo "Deployed to Dev..."

  deploy-prod:
    needs: build_and_deploy-dev
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://moviephobics.netlify.app 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            version=$(echo "$latest_tag" | sed 's/v//')
            IFS='.' read -r major minor patch <<< "$version"
            new_patch=$((patch + 1))
            new_tag="v${major}.${minor}.${new_patch}"
          fi
          echo "New tag: $new_tag"
          echo "TAG_VERSION=$new_tag" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        id: create_tag
        run: |
          git tag $TAG_VERSION
          git push origin $TAG_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_VERSION }}
          release_name: ${{ env.TAG_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploying to Production
        run: echo "Deploying to Production..."

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |          
          BUILD_HOOK_URL="$NETLIFY_BUILD_HOOK_URL?trigger_branch=main&clear_cache=true"
          
          # Trigger the build hook
          curl -X POST "$BUILD_HOOK_URL" \
          -H "Content-Type: application/json"

      - name: Deploy to Production
        run: echo "Deployed to Production..."
